
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pascal
 */
public class VelocityDlg extends javax.swing.JDialog {

    
    private boolean ok = false;
    private Measurement m;
    
    private DateTimeFormatter date = DateTimeFormatter.ofPattern("dd.MM.yyyy");
    private DateTimeFormatter time = DateTimeFormatter.ofPattern("HH:mm");

    public VelocityDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public boolean isOk() {
        return ok;
    }

    public Measurement getM() {
        return m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_time = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_kenn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_gemessen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_erlaubt = new javax.swing.JTextField();
        bt_ok = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Datum:");
        getContentPane().add(jLabel1);
        getContentPane().add(tf_date);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Uhrzeit:");
        getContentPane().add(jLabel2);
        getContentPane().add(tf_time);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Kennzeichen:");
        getContentPane().add(jLabel3);
        getContentPane().add(tf_kenn);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("V-Gemessen:");
        getContentPane().add(jLabel4);
        getContentPane().add(tf_gemessen);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("V-Erlaubt:");
        getContentPane().add(jLabel5);
        getContentPane().add(tf_erlaubt);

        bt_ok.setText("Übernehmen");
        bt_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_okActionPerformed(evt);
            }
        });
        getContentPane().add(bt_ok);

        bt_cancel.setText("Abbrechen");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_okActionPerformed
        boolean bool = false;
        String zeichen = tf_kenn.getText();
        ok = false;
        try
        {
        double uebertr;
        double gem = Double.parseDouble(tf_gemessen.getText());
        double erl = Double.parseDouble(tf_erlaubt.getText());
        uebertr = gem-erl;
        m = new Measurement(LocalDate.parse(tf_date.getText(), date), 
                           LocalTime.parse(tf_time.getText(), time), tf_kenn.getText(), 
                           Double.parseDouble(tf_gemessen.getText()),Double.parseDouble(tf_erlaubt.getText()), uebertr);
        bool = false;
        }
        catch(Exception e)
        {
        System.out.println("Fehler: "+e.toString());
        bool = true;
        JOptionPane.showMessageDialog(this,"Bitte überpfrügen Sie Datum und Zeit Formate und das Kennzeichenformat");
        }
        ok = true;
        this.setVisible(bool);

    }//GEN-LAST:event_bt_okActionPerformed

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
        ok = false;
        this.setVisible(ok);
    }//GEN-LAST:event_bt_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VelocityDlg dialog = new VelocityDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tf_date;
    private javax.swing.JTextField tf_erlaubt;
    private javax.swing.JTextField tf_gemessen;
    private javax.swing.JTextField tf_kenn;
    private javax.swing.JTextField tf_time;
    // End of variables declaration//GEN-END:variables
}
