
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pascal
 */
public class VelocityGUI extends javax.swing.JFrame {

    private VelocityTableModel model = new VelocityTableModel();
    
    public VelocityGUI() {
        initComponents();
        table.setModel(model);
        table.setComponentPopupMenu(popUpMenu);
        //table.setDefaultRenderer(Object.class, new VelocityTableRenderer());
        model.add(new Measurement(LocalDate.now(), LocalTime.now(), "abc", 10,10,0));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMenu = new javax.swing.JPopupMenu();
        Hinzufügen = new javax.swing.JMenuItem();
        Löschen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Durschnitt = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        onSave = new javax.swing.JMenuItem();
        onLoad = new javax.swing.JMenuItem();

        Hinzufügen.setText("Hinzufügen");
        Hinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HinzufügenActionPerformed(evt);
            }
        });
        popUpMenu.add(Hinzufügen);

        Löschen.setText("Löschen");
        Löschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LöschenActionPerformed(evt);
            }
        });
        popUpMenu.add(Löschen);
        popUpMenu.add(jSeparator1);

        Durschnitt.setText("Durschnitt");
        Durschnitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurschnittActionPerformed(evt);
            }
        });
        popUpMenu.add(Durschnitt);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setComponentPopupMenu(popUpMenu);
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        onSave.setText("Save");
        jMenu1.add(onSave);

        onLoad.setText("Load");
        jMenu1.add(onLoad);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HinzufügenActionPerformed
        //Hinzufügen
        VelocityDlg dlg = new VelocityDlg(this, true);
        dlg.setVisible(true);
        if (dlg.isOk()) {
            Measurement m = dlg.getM();
            model.add(m);
        }
    }//GEN-LAST:event_HinzufügenActionPerformed

    private void LöschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LöschenActionPerformed
        //Löschen
        int i = table.getSelectedRow();
        model.remove(i);
    }//GEN-LAST:event_LöschenActionPerformed

    private void DurschnittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurschnittActionPerformed
        //Durschnitt
        double average = model.averageGemessen();
        JOptionPane.showMessageDialog(null, "Durschnitt: " + average);
    }//GEN-LAST:event_DurschnittActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VelocityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Durschnitt;
    private javax.swing.JMenuItem Hinzufügen;
    private javax.swing.JMenuItem Löschen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem onLoad;
    private javax.swing.JMenuItem onSave;
    private javax.swing.JPopupMenu popUpMenu;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
